app = "gkin-amstelveen-black-field-1417"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python -c \"print('Release command executed')\""

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
