# fly.toml app configuration file generated for gkin-amstelveen on 2026-05-20T20:22:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gkin-amstelveen'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = "python -c \"print('Release command executed')\""

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
